In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Q4.1 Visualize the two gray scale images corresponding to the first line in three.txt and the first line in eight.txt.

In [96]:
def img_plot(filename = None ,img_vec = None, plot_name = None):
    if filename != None:
        f = open(filename,'r')
        content = f.readline()
        content = content.split('\n')[0]
        content = content.strip()
        img_vec = list(content.split(' '))
        img_vec = [int(img_vec[i]) for i in range(len(img_vec))]
        plot_name = filename.replace('.txt','')
    img = []
    for i in range(16):
        tmp = []
        for j in range(16):
            tmp.append(img_vec[16*i+j])
        img.append(tmp)
    plt.imshow(img)
    plt.savefig(plot_name.replace('.txt',''))
    plt.clf()

In [97]:
three = img_plot('three.txt')
eight = img_plot('eight.txt')

<Figure size 432x288 with 0 Axes>

## Q4.2

In [99]:
def integrate(file1,file2):
    f1 = open(file1,'r')
    f2 = open(file2,'r')
    X = []
    line = f1.readline()
    while(line):
        line = line.replace('\n',' ')
        line = line.strip()
        X_tmp = list(line.split(' '))
        X_tmp = [int(X_tmp[i]) for i in range(len(X_tmp))]
        X.append(X_tmp)
        line = f1.readline()
    line = f2.readline()
    while(line):
        line = line.replace('\n',' ')
        line = line.strip()
        X_tmp = [int(X_tmp[i]) for i in range(len(X_tmp))]
        X.append(X_tmp)
        line = f2.readline()
    return X

In [100]:
X = integrate('three.txt','eight.txt')

In [111]:
# get mean of X
y = [0]*256
for i in range(len(X)):
    for j in range(len(y)):
        y[j] += X[i][j]
y = [v/256 for v in y]

In [112]:
img_plot(img_vec = y, plot_name = 'q42')

<Figure size 432x288 with 0 Axes>

## Q4.3 

In [113]:
# center X
X_center = []
for x in X:
    tmp = [(x[i] - y[i]) for i in range(len(x))]
    X_center.append(tmp)

In [122]:
X_center  = np.array(X_center)
S = np.matmul(X_center.T,X_center)/(len(y)-1)

In [132]:
S_sub = S[:5,:5]
for s in S_sub:
    print(s)

[ 87.46948912 227.6370481   57.48734107   6.66785003  -1.99574334]
[ 227.6370481  1288.66263787  448.44448912   72.46379442   -8.71870787]
[ 57.48734107 448.44448912 866.12206744 305.86639285  13.6765041 ]
[  6.66785003  72.46379442 305.86639285 526.20107613 228.00078699]
[ -1.99574334  -8.71870787  13.6765041  228.00078699 363.18351811]
